#ifndef CPU_H
#define CPU_H

#include <array>
#include <cstddef>
#include <cstdint>

#include "commit.h"
#include "instruction.h"
#include "memory.h"

// ============================================================
// RV32I ARCHITECTURAL REFERENCE CPU
// ============================================================
//
// This is a sequential architectural model.
//
// It does NOT model:
//   - pipeline stages
//   - forwarding
//   - stalls
//   - flush timing
//
// Every successful step() executes and retires exactly one
// architectural instruction and produces one CommitInfo.
//
// ============================================================

class CPU
{
public:

    static constexpr std::size_t NUM_REGISTERS = 32;

    // ========================================================
    // CONSTRUCTOR / RESET
    // ========================================================

    explicit CPU(Memory& memory);

    void reset(uint32_t resetPC = 0);


    // ========================================================
    // EXECUTION
    // ========================================================

    // Execute and retire one instruction.
    bool step();

    // Execute until program completion or instruction limit.
    bool run(std::size_t maxInstructions);


    // ========================================================
    // ARCHITECTURAL STATE
    // ========================================================

    uint32_t getPC() const;

    uint32_t getRegister(uint8_t index) const;

    void setRegister(
        uint8_t index,
        uint32_t value
    );

    uint64_t getInstructionCount() const;


    // ========================================================
    // COMMIT INTERFACE
    // ========================================================

    // Commit information generated by the most recently
    // retired instruction.
    const CommitInfo& getLastCommit() const;


    // ========================================================
    // DEBUG
    // ========================================================

    void dumpRegisters() const;


private:

    // ========================================================
    // ARCHITECTURAL STATE
    // ========================================================

    uint32_t pc;

    std::array<uint32_t, NUM_REGISTERS> registers;

    Memory& memory;

    uint64_t instructionCount;


    // ========================================================
    // COMMIT STATE
    // ========================================================

    CommitInfo lastCommit;


    // ========================================================
    // MAIN EXECUTION DISPATCH
    // ========================================================

    bool execute(
        const DecodedInstruction& instruction
    );


    // ========================================================
    // REGISTER WRITEBACK
    // ========================================================

    void writeRegister(
        uint8_t rd,
        uint32_t value
    );


    // ========================================================
    // INSTRUCTION GROUP EXECUTION
    // ========================================================

    void executeInteger(
        const DecodedInstruction& instruction
    );

    void executeLoad(
        const DecodedInstruction& instruction
    );

    void executeStore(
        const DecodedInstruction& instruction
    );

    void executeBranch(
        const DecodedInstruction& instruction
    );

    void executeJump(
        const DecodedInstruction& instruction
    );

    void executeUpperImmediate(
        const DecodedInstruction& instruction
    );
};

#endif // CPU_H