#!/bin/bash

set -u

echo "=================================================="
echo "       RV32I DIFFERENTIAL REGRESSION"
echo "=================================================="
echo

RTL_SIM="sim/cpu_sim"
CPP_TRACE="cpp_model/build/trace_model"
COMPARATOR="cpp_model/build/compare_traces"

TRACE_DIR="traces/differential"

mkdir -p "$TRACE_DIR"

# ============================================================
# TEST DEFINITIONS
#
# Format:
#
#     name:test_id:program
#
# No architectural instruction count is required anymore.
# The C++ model terminates naturally when its PC leaves the
# loaded program.
# ============================================================

TESTS=(
    "alu:1:tests/directed/alu.hex"
    "forwarding:2:tests/directed/forwarding.hex"
    "load_store:3:tests/directed/load_store.hex"
    "load_use:4:tests/directed/load_use.hex"
    "beq_taken:5:tests/directed/beq_taken.hex"
    "beq_not_taken:6:tests/directed/beq_not_taken.hex"
    "branches:7:tests/directed/branches.hex"
    "jal:8:tests/directed/jal.hex"
    "jalr:9:tests/directed/jalr.hex"
    "full_regression:10:tests/directed/full_regression.hex"
)

passed=0
failed=0


# ============================================================
# CHECK REQUIRED FILES
# ============================================================

if [ ! -f "$RTL_SIM" ]; then
    echo "[ERROR] Missing RTL simulation executable:"
    echo "        $RTL_SIM"
    exit 1
fi

if [ ! -x "$CPP_TRACE" ]; then
    echo "[ERROR] Missing C++ trace model:"
    echo "        $CPP_TRACE"
    exit 1
fi

if [ ! -x "$COMPARATOR" ]; then
    echo "[ERROR] Missing differential comparator:"
    echo "        $COMPARATOR"
    exit 1
fi


# ============================================================
# RUN DIFFERENTIAL TESTS
# ============================================================

for test in "${TESTS[@]}"; do

    IFS=':' read -r \
        name \
        test_id \
        program \
        <<< "$test"

    echo "--------------------------------------------------"
    echo "[DIFF TEST] $name"
    echo "--------------------------------------------------"

    rtl_trace="$TRACE_DIR/rtl_${name}.log"
    cpp_trace="$TRACE_DIR/cpp_${name}.log"
    diff_log="$TRACE_DIR/diff_${name}.log"


    # ========================================================
    # RTL EXECUTION
    # ========================================================

    vvp "$RTL_SIM" \
        +TEST_ID="$test_id" \
        +PROGRAM="$program" \
        > "$rtl_trace" 2>&1

    rtl_status=$?

    if [ "$rtl_status" -ne 0 ]; then

        echo "[FAIL] RTL simulation failed"
        echo "       Log: $rtl_trace"
        echo

        failed=$((failed + 1))

        continue
    fi


    # ========================================================
    # C++ REFERENCE EXECUTION
    #
    # No instruction count anymore.
    # Execution terminates when PC leaves the loaded program.
    # ========================================================

    "$CPP_TRACE" \
        "$program" \
        > "$cpp_trace" 2>&1

    cpp_status=$?

    if [ "$cpp_status" -ne 0 ]; then

        echo "[FAIL] C++ reference model failed"
        echo "       Log: $cpp_trace"
        echo

        failed=$((failed + 1))

        continue
    fi


    # ========================================================
    # DETERMINE ARCHITECTURAL COMMIT COUNT
    #
    # Count the commits generated by the C++ golden model.
    # This becomes the comparison length.
    # ========================================================

    commit_count=$(
        grep -c "^COMMIT" "$cpp_trace" || true
    )


    if [ "$commit_count" -eq 0 ]; then

        echo "[FAIL] No C++ architectural commits generated"
        echo "       Log: $cpp_trace"
        echo

        failed=$((failed + 1))

        continue
    fi


    # ========================================================
    # DIFFERENTIAL COMPARISON
    # ========================================================

    "$COMPARATOR" \
        "$rtl_trace" \
        "$cpp_trace" \
        "$commit_count" \
        > "$diff_log" 2>&1

    diff_status=$?


    if [ "$diff_status" -eq 0 ]; then

        echo "[PASS] $name"

        passed=$((passed + 1))

    else

        echo "[FAIL] $name"
        echo

        cat "$diff_log"

        failed=$((failed + 1))

    fi

    echo

done


# ============================================================
# SUMMARY
# ============================================================

total=$((passed + failed))

echo
echo "=================================================="
echo "       DIFFERENTIAL REGRESSION SUMMARY"
echo "=================================================="
echo

echo "Total tests : $total"
echo "Passed      : $passed"
echo "Failed      : $failed"

echo


# ============================================================
# FINAL STATUS
# ============================================================

if [ "$failed" -eq 0 ]; then

    echo "=================================================="
    echo "       DIFFERENTIAL REGRESSION PASSED"
    echo "=================================================="

    exit 0

else

    echo "=================================================="
    echo "       DIFFERENTIAL REGRESSION FAILED"
    echo "=================================================="
    echo
    echo "Trace files are available in:"
    echo
    echo "    $TRACE_DIR/"

    exit 1
fi